# This is a basic workflow that is manually triggered

name: Kit Docker Image Release

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      # 試験実施バージョンの指定
      test_version:
        description: 'Passed test version'
        default: test.
        required: true
      # リリースバージョンの指定
      release_version:
        description: 'Release version'
        default: 4.x.x
        required: true
      # バージョン形式のチェック有無
      check_on:
        description: 'Check validation input version'
        default: 'on'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Check Input Test Version
      if: ${{ github.event.inputs.check_on == 'on' }}
      run: |
        if echo "${{ github.event.inputs.test_version }}" | grep -E "^test\.[1-9][0-9]*$"; then
          echo "valid test version"
        else
          echo "invalid test version"
          exit 1
        fi

    - name: Check Input Release Version
      if: ${{ github.event.inputs.check_on == 'on' }}
      run: |
        if echo "${{ github.event.inputs.release_version }}" | grep -E "^4\.[0-9]+\.[0-9]+$"; then
          echo "valid test version"
        else
          echo "invalid test version"
          echo "invalid test version"
        fi

    # Runs a single command using the runners shell
    - name: Echo versions
      run: |
        echo "TEST-VERSION ${{ github.event.inputs.test_version }}"
        echo "RELEASE-VERSION ${{ github.event.inputs.release_version }}"
